try:
    print(x)
except:
    print("Error happens!")
